// HMCL Nex JavaScript HelloWorld Plugin (Node.js runtime)
//
// JavaScript plugins run in the HMCL-managed Node.js runtime as separate
// processes. Each lifecycle event invokes this script as:
//     node main.js <event>
// Available events: onLoad, onEnable, onDisable, onUnload
//
// Plugin metadata is provided via environment variables:
//   HMCL_PLUGIN_EVENT     - current lifecycle event
//   HMCL_PLUGIN_ID        - plugin id from plugin.json
//   HMCL_PLUGIN_NAME      - plugin display name
//   HMCL_PLUGIN_VERSION   - plugin version
//   HMCL_PLUGIN_DIR       - extracted plugin directory
//   HMCL_PLUGIN_DATA_DIR  - launcher data directory
//   HMCL_VERSION          - launcher version

'use strict';

const fs = require('fs');
const path = require('path');

const event = process.argv[2] || process.env.HMCL_PLUGIN_EVENT || 'unknown';
const pluginDir = process.env.HMCL_PLUGIN_DIR || __dirname;
const pluginName = process.env.HMCL_PLUGIN_NAME || 'JavaScript HelloWorld';
const hmclVersion = process.env.HMCL_VERSION || 'unknown';

const MESSAGE_PREFIX = 'HMCL_PLUGIN_MESSAGE:';

function send(message) {
    process.stdout.write(`${MESSAGE_PREFIX}${JSON.stringify({
        protocol: 'hmcl-ui-v1',
        ...message
    })}\n`);
}

function log(message) {
    const line = `${new Date().toISOString()} [${event}] ${message}\n`;
    // Console output is captured into the HMCL log
    process.stdout.write(line);
    // Also persist to a log file in the plugin directory
    try {
        fs.appendFileSync(path.join(pluginDir, 'javascript-helloworld.log'), line);
    } catch (e) {
        // ignore
    }
}

switch (event) {
    case 'onLoad':
        log(`${pluginName} loaded on HMCL ${hmclVersion} (Node.js ${process.version})`);
        break;

    case 'onEnable':
        log(`${pluginName} enabled`);
        // Example: write a data file when the plugin is enabled
        try {
            fs.writeFileSync(path.join(pluginDir, 'data.txt'),
                `Hello from Node.js ${process.version}!\nEnabled at: ${new Date().toISOString()}\n`);
            log('data.txt written');
        } catch (e) {
            log('Failed to write data.txt: ' + e.message);
        }

        // Declare a real JavaFX control tree. HMCL creates these controls in
        // its JVM; this Node.js process never accesses JavaFX classes directly.
        send({
            sidebar: {
                title: 'JavaScript HelloWorld',
                page: {
                    type: 'vbox',
                    spacing: 16,
                    children: [
                        { type: 'title', text: `🎉 ${pluginName}` },
                        {
                            type: 'label',
                            text: 'This is a real JavaFX page declared by JavaScript and rendered by HMCL.',
                            variant: 'secondary'
                        },
                        { type: 'separator' },
                        { type: 'subtitle', text: 'Runtime information' },
                        { type: 'label', text: `Node.js ${process.version}  ·  HMCL ${hmclVersion}` },
                        { type: 'textField', id: 'name', prompt: 'Enter your name', text: 'Player' },
                        {
                            type: 'hbox',
                            spacing: 10,
                            children: [
                                { type: 'button', text: 'Say hello', event: 'sayHello', primary: true },
                                { type: 'button', text: 'Show dialog', event: 'showDialog' }
                            ]
                        },
                        {
                            type: 'label',
                            id: 'status',
                            text: 'Button events are sent back to the isolated Node.js plugin.',
                            variant: 'success'
                        }
                    ]
                }
            }
        });
        break;

    case 'onUiEvent': {
        const eventId = process.env.HMCL_UI_EVENT_ID || '';
        let values = {};
        try {
            values = JSON.parse(process.env.HMCL_UI_VALUES || '{}');
        } catch (e) {
            log('Invalid HMCL_UI_VALUES: ' + e.message);
        }

        if (eventId === 'sayHello') {
            const name = String(values.name || 'Player').trim() || 'Player';
            send({
                actions: [
                    { type: 'setText', target: 'status', text: `Hello, ${name}! Response generated by Node.js ${process.version}.` }
                ]
            });
        } else if (eventId === 'showDialog') {
            send({
                actions: [
                    {
                        type: 'dialog',
                        title: 'JavaScript plugin',
                        message: 'This HMCL dialog was requested by an isolated Node.js event handler.',
                        level: 'info'
                    }
                ]
            });
        } else {
            log(`Unknown UI event: ${eventId}`);
        }
        break;
    }

    case 'onDisable':
        log(`${pluginName} disabled`);
        break;

    case 'onUnload':
        log(`${pluginName} unloaded`);
        break;

    default:
        log(`Unknown lifecycle event: ${event}`);
        break;
}